name: Start project rebuild due to data changes

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  apply-empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create Empty Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "ci: forcing rebuild due to new data changes" --allow-empty
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.PAT_TOKEN_FRONTEND_MENTOR }}



